modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory
issueTrackerURL="https://github.com/bl4ckscor3/ChanceGlobe/issues"
displayURL="http://minecraft.curseforge.com/projects/chance-globe"
authors="bl4ckscor3"

[[mods]] #mandatory
modId="chanceglobe" #mandatory
version="v1.3" #mandatory
displayName="Chance Globe" #mandatory
description='''Spawns a random block or item upon placing it down!''' #mandatory

[[dependencies.chanceglobe]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.chanceglobe]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14,1.15)"
    ordering="NONE"
    side="BOTH"