modLoader="javafml" #mandatory
loaderVersion="[33,)" #mandatory
license="GNU GPL v3.0 https://github.com/bl4ckscor3/ChanceGlobe/blob/1.16/LICENSE"
issueTrackerURL="https://github.com/bl4ckscor3/ChanceGlobe/issues"
displayURL="http://minecraft.curseforge.com/projects/chance-globe"
authors="bl4ckscor3"

[[mods]] #mandatory
modId="chanceglobe" #mandatory
version="v1.3.4" #mandatory
displayName="Chance Globe" #mandatory
description='''Spawns a random block or item upon placing it down!''' #mandatory

[[dependencies.chanceglobe]]
    modId="forge"
    mandatory=true
    versionRange="[33,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.chanceglobe]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,1.17)"
    ordering="NONE"
    side="BOTH"