modLoader="javafml"
loaderVersion="[1,)"
license="MIT https://github.com/bl4ckscor3/ChanceGlobe/blob/1.20.4/LICENSE"

[[mods]]
	modId="chanceglobe"
	version="${file.jarVersion}"
	displayName="Chance Globe"
	description='''Spawns a random block or item upon placing it down!'''
	issueTrackerURL="https://github.com/bl4ckscor3/ChanceGlobe/issues"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/chance-globe"
	authors="bl4ckscor3"

[[dependencies.chanceglobe]]
    modId="neoforge"
    mandatory=true
    versionRange="[20.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.chanceglobe]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.3,1.21)"
    ordering="NONE"
    side="BOTH"