modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory

[[mods]] #mandatory
	modId="chanceglobe" #mandatory
	version="${version}" #mandatory
	displayName="Chance Globe" #mandatory
	description='''Spawns a random block or item upon placing it down!''' #mandatory
	issueTrackerURL="https://github.com/bl4ckscor3/ChanceGlobe/issues"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/chance-globe"
	authors="bl4ckscor3"

[[dependencies.chanceglobe]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.chanceglobe]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15,1.16)"
    ordering="NONE"
    side="BOTH"