modLoader="javafml" #mandatory
loaderVersion="[33,)" #mandatory
license="GNU GPL v3.0 https://github.com/bl4ckscor3/ChanceGlobe/blob/1.16/LICENSE"

[[mods]] #mandatory
	modId="chanceglobe" #mandatory
	version="${version}" #mandatory
	displayName="Chance Globe" #mandatory
	description='''Spawns a random block or item upon placing it down!''' #mandatory
	issueTrackerURL="https://github.com/bl4ckscor3/ChanceGlobe/issues"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/chance-globe"
	authors="bl4ckscor3"

[[dependencies.chanceglobe]]
    modId="forge"
    mandatory=true
    versionRange="[33,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.chanceglobe]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,1.17)"
    ordering="NONE"
    side="BOTH"