modLoader="javafml"
loaderVersion="[41,)"
license="GNU GPL v3.0 https://github.com/bl4ckscor3/ChanceGlobe/blob/1.19/LICENSE"

[[mods]]
	modId="chanceglobe"
	version="${file.jarVersion}"
	displayName="Chance Globe"
	description='''Spawns a random block or item upon placing it down!'''
	issueTrackerURL="https://github.com/bl4ckscor3/ChanceGlobe/issues"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/chance-globe"
	authors="bl4ckscor3"

[[dependencies.chanceglobe]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.64,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.chanceglobe]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"