license="MIT https://github.com/bl4ckscor3/ChanceGlobe/blob/1.21.6/LICENSE"

[[mods]]
	modId="chanceglobe"
	version="${file.jarVersion}"
	displayName="Chance Globe"
	description='''Spawns a random block or item upon placing it down!'''
	issueTrackerURL="https://github.com/bl4ckscor3/ChanceGlobe/issues"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/chance-globe"
	authors="bl4ckscor3"

[[dependencies.chanceglobe]]
    modId="neoforge"
    type="required"
    versionRange="[21,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.chanceglobe]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.6,1.22)"
    ordering="NONE"
    side="BOTH"